export const deviceConstants = {
    CREATE_REQUEST: 'DEVICE_CREATE_REQUEST',
    CREATE_SUCCESS: 'DEVICE_CREATE_SUCCESS',
    CREATE_FAILURE: 'DEVICE_CREATE_FAILURE',
    ASSIGN_REQUEST: 'DEVICE_ASSIGN_REQUEST',
    ASSIGN_SUCCESS: 'DEVICE_ASSIGN_SUCCESS',
    ASSIGN_FAILURE: 'DEVICE_ASSIGN_FAILURE',
    FIND_BY_ID_REQUEST: 'DEVICE_FIND_BY_ID_REQUEST',
    FIND_BY_ID_SUCCESS: 'DEVICE_FIND_BY_ID_SUCCESS',
    FIND_BY_ID_FAILURE: 'DEVICE_FIND_BY_ID_FAILURE',
    FIND_ALL_UNASSIGNED_REQUEST: 'DEVICE_FIND_ALL_UNASSIGNED_REQUEST',
    FIND_ALL_UNASSIGNED_SUCCESS: 'DEVICE_FIND_ALL_UNASSIGNED_SUCCESS',
    FIND_ALL_UNASSIGNED_FAILURE: 'DEVICE_FIND_ALL_UNASSIGNED_FAILURE',
}
