export const deviceConstants = {
    CREATE_REQUEST: 'DEVICE_CREATE_REQUEST',
    CREATE_SUCCESS: 'DEVICE_CREATE_SUCCESS',
    CREATE_FAILURE: 'DEVICE_CREATE_FAILURE',
    // FIND_BY_ID_REQUEST: 'DEVICE_FIND_BY_ID_REQUEST',
    // FIND_BY_ID_SUCCESS: 'DEVICE_FIND_BY_ID_SUCCESS',
    // FIND_BY_ID_FAILURE: 'DEVICE_FIND_BY_ID_FAILURE',
    // FIND_ALL_REQUEST: 'DEVICE_FIND_ALL_REQUEST',
    // FIND_ALL_SUCCESS: 'DEVICE_FIND_ALL_SUCCESS',
    // FIND_ALL_FAILURE: 'DEVICE_FIND_ALL_FAILURE',
}
