export const patientConstants = {
    CREATE_REQUEST: 'PATIENT_CREATE_REQUEST',
    CREATE_SUCCESS: 'PATIENT_CREATE_SUCCESS',
    CREATE_FAILURE: 'PATIENT_CREATE_FAILURE',
    FIND_BY_ID_REQUEST: 'PATIENT_FIND_BY_ID_REQUEST',
    FIND_BY_ID_SUCCESS: 'PATIENT_FIND_BY_ID_SUCCESS',
    FIND_BY_ID_FAILURE: 'PATIENT_FIND_BY_ID_FAILURE',
    FIND_ALL_REQUEST: 'PATIENT_FIND_ALL_REQUEST',
    FIND_ALL_SUCCESS: 'PATIENT_FIND_ALL_SUCCESS',
    FIND_ALL_FAILURE: 'PATIENT_FIND_ALL_FAILURE',


}
