export const practitionerConstants = {
    CREATE_REQUEST: 'PRACTITIONER_CREATE_REQUEST',
    CREATE_SUCCESS: 'PRACTITIONER_CREATE_SUCCESS',
    CREATE_FAILURE: 'PRACTITIONER_CREATE_FAILURE',
    FIND_BY_ID_REQUEST: 'PRACTITIONER_FIND_BY_ID_REQUEST',
    FIND_BY_ID_SUCCESS: 'PRACTITIONER_FIND_BY_ID_SUCCESS',
    FIND_BY_ID_FAILURE: 'PRACTITIONER_FIND_BY_ID_FAILURE',
}
