export const practitionerConstants = {
    CREATE_REQUEST: 'PRACTITIONER_CREATE_REQUEST',
    CREATE_SUCCESS: 'PRACTITIONER_CREATE_SUCCESS',
    CREATE_FAILURE: 'PRACTITIONER_CREATE_FAILURE',
    FIND_BY_ID_REQUEST: 'PRACTITIONER_FIND_BY_ID_REQUEST',
    FIND_BY_ID_SUCCESS: 'PRACTITIONER_FIND_BY_ID_SUCCESS',
    FIND_BY_ID_FAILURE: 'PRACTITIONER_FIND_BY_ID_FAILURE',
    GET_ALL_REQUEST: 'PRACTITIONER_GET_ALL_REQUEST',
    GET_ALL_SUCCESS: 'PRACTITIONER_GET_ALL_SUCCESS',
    GET_ALL_FAILURE: 'PRACTITIONER_GET_ALL_FAILURE',
    CARE_MANAGERS_GET_ALL_REQUEST: 'PRACTITIONER_CARE_MANAGERS_GET_ALL_REQUEST',
    CARE_MANAGERS_GET_ALL_SUCCESS: 'PRACTITIONER_CARE_MANAGERS_GET_ALL_SUCCESS',
    CARE_MANAGERS_GET_ALL_FAILURE: 'PRACTITIONER_CARE_MANAGERS_GET_ALL_FAILURE',
}
